---
- name: Include Linux system tasks
  ansible.builtin.include_tasks: linux.yml
  when: ansible_os_family != 'Windows'
  tags: [system]

- name: Include Windows system tasks
  ansible.builtin.include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
  tags: [system]
