- name: Configurar prácticas seguras de usuario en Windows
  hosts: win_clients, winserver
  tasks:
    - name: Configurar bloqueo automático tras inactividad
      win_security_policy:
        name: "InteractiveLogon_RequireActiveSessionLock"
        option_value: true
