- name: Instalar y configurar antivirus en Windows
  hosts: windows
  tasks:
    - name: Asegurar que Windows Defender est√° habilitado
      win_service:
        name: "WinDefend"
        state: started
