---
- name: Include Linux schedule tasks
  ansible.builtin.include_tasks: linux.yml
  when: ansible_os_family != 'Windows'
  tags: [schedule]

- name: Include Windows schedule tasks
  ansible.builtin.include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
  tags: [schedule]
