---
- name: Include Linux users tasks
  ansible.builtin.include_tasks: linux.yml
  when: ansible_os_family != 'Windows'
  tags: [users]

- name: Include Windows users tasks
  ansible.builtin.include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
  tags: [users]
