- name: Instalar y configurar antivirus en Debian
  hosts: debian_clients
  tasks:
    - name: Instalar ClamAV (Antivirus)
      apt:
        name: clamav
        state: present
    - name: Asegurar que ClamAV est√° habilitado
      service:
        name: clamav-freshclam
        state: started
        enabled: yes
