- name: Configurar prácticas seguras de usuario en Debian
  hosts: debian_clients
  tasks:
    - name: Configurar bloqueo automático tras inactividad
      lineinfile:
        path: /etc/profile
        regexp: '^TMOUT'
        line: 'TMOUT=600'
